## DATABASE CONFIGURATION

spring.datasource.url=jdbc:mysql://localhost:3306/onedesk
spring.datasource.username=OneDesK_user
spring.datasource.password=lololi202
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver