
CREATE TABLE Persona (
    ID INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    contraseña VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Deuda (
    ID INT NOT NULL AUTO_INCREMENT,
    monto INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Usuario (
    ID INT NOT NULL,
    ID_DEUDA INT NOT NULL,
    topeCredito INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);

CREATE TABLE Producto (
    ID INT AUTO_INCREMENT,
    genetica VARCHAR(255) NOT NULL UNIQUE,
    precio INT NOT NULL,
    stock INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Indoor (
    ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID)
);

CREATE TABLE Planta (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_INDOOR INT NOT NULL,
    genetica VARCHAR(255) NOT NULL,
    fechaPlantado DATE NOT NULL,
    fechaGerminado DATE NOT NULL,
    fechaCosecha DATE ,
    tiempoLuz INT NOT NULL,
    tiempoRegado INT NOT NULL,
    tiempoVentilacion INT NOT NULL,
    ultimoRegado DATETIME,
    ultimoLuz DATETIME,
    ultimoVentilacion DATETIME,
    luz BOOLEAN NOT NULL,
    ventilador BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Compra (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    fechaCompra DATE NOT NULL,
    precio INT NOT NULL,
    pagado BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ItemCompra (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_COMPRA INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    cantidad INT NOT NULL,
    precioUnitario INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Empleado (
    ID INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE EmpleadoIndoor (
    ID INT NOT NULL,
    salarioMensual INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Evento (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_INDOOR INT NOT NULL,
    ID_PLANTA INT NOT NULL,
    realizado BOOLEAN NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Trabaja (
    ID_EMPLEADO_INDOOR INT NOT NULL,
    ID_INDOOR INT NOT NULL,
    PRIMARY KEY (ID_EMPLEADO_INDOOR, ID_INDOOR)
);

CREATE TABLE RegistroProduccion (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_EMPLEADO_INDOOR INT NOT NULL,
    ID_INDOOR INT NOT NULL,
    ID_PLANTA INT NOT NULL,
    cantidad INT NOT NULL,
    fechaRegistro DATE NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    PRIMARY KEY (ID)
);


ALTER TABLE Usuario
    ADD CONSTRAINT fk_Persona_ID_Usuario
        FOREIGN KEY (ID) REFERENCES Persona(ID)
        ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Usuario
    ADD CONSTRAINT fk_Deuda_ID_Usuario
        FOREIGN KEY (ID_DEUDA) REFERENCES Deuda(ID)
        ON DELETE NO ACTION ON UPDATE CASCADE;


ALTER TABLE Planta
    ADD CONSTRAINT fk_Indoor_ID_Planta
        FOREIGN KEY (ID_INDOOR) REFERENCES Indoor(ID)
        ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE Compra
    ADD CONSTRAINT fk_Usuario_ID_Compra
        FOREIGN KEY (ID_USUARIO) REFERENCES Usuario(ID)
        ON DELETE NO ACTION ON UPDATE CASCADE;


ALTER TABLE ItemCompra
    ADD CONSTRAINT fk_Compra_ID_ItemCompra
        FOREIGN KEY (ID_COMPRA) REFERENCES Compra(ID)
        ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ItemCompra
    ADD CONSTRAINT fk_Producto_ID_ItemCompra
        FOREIGN KEY (ID_PRODUCTO) REFERENCES Producto(ID)
        ON DELETE NO ACTION ON UPDATE CASCADE;


ALTER TABLE Empleado
    ADD CONSTRAINT fk_Empleado_ID_Persona
        FOREIGN KEY (ID) REFERENCES Persona(ID)
        ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE EmpleadoIndoor
    ADD CONSTRAINT fk_Empleado_ID_EmpleadoIndoor
        FOREIGN KEY (ID) REFERENCES Empleado(ID)
        ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE Evento
    ADD CONSTRAINT fk_Indoor_ID_Evento
        FOREIGN KEY (ID_INDOOR) REFERENCES Indoor(ID)
        ON DELETE NO ACTION ON UPDATE CASCADE;

ALTER TABLE Evento
    ADD CONSTRAINT fk_Planta_ID_Evento
        FOREIGN KEY (ID_PLANTA) REFERENCES Planta(ID)
        ON DELETE NO ACTION ON UPDATE CASCADE;


ALTER TABLE Trabaja
    ADD CONSTRAINT fk_EmpleadoIndoor_ID_Trabaja
        FOREIGN KEY (ID_EMPLEADO_INDOOR) REFERENCES EmpleadoIndoor(ID)
        ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Trabaja
    ADD CONSTRAINT fk_Indoor_ID_Trabaja
        FOREIGN KEY (ID_INDOOR) REFERENCES Indoor(ID)
        ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE RegistroProduccion
    ADD CONSTRAINT fk_Indoor_ID_RegistroProduccion
        FOREIGN KEY (ID_INDOOR) REFERENCES Indoor(ID)
        ON DELETE NO ACTION ON UPDATE CASCADE;

ALTER TABLE RegistroProduccion
    ADD CONSTRAINT fk_EmpleadoIndoor_ID_RegistroProduccion
        FOREIGN KEY (ID_EMPLEADO_INDOOR) REFERENCES EmpleadoIndoor(ID)
        ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RegistroProduccion
    ADD CONSTRAINT fk_Producto_ID_RegistroProduccion
        FOREIGN KEY (ID_PRODUCTO) REFERENCES Producto(ID)
        ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RegistroProduccion
    ADD CONSTRAINT fk_Planta_ID_RegistroProduccion
        FOREIGN KEY (ID_PLANTA) REFERENCES Planta(ID)
        ON DELETE NO ACTION ON UPDATE NO ACTION;
